version: "3.9"
services:
  tvvactivemq:
    container_name: tvv-activemq
    image: rmohr/activemq:latest
    restart: always
    ports:
      # jakarta messaging
      - "61616:61616"
      # web console
      - "8161:8161"
  tvvpostgres:
    container_name: tvv-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=teamd
      - POSTGRES_PASSWORD=TeamSpirit23!
      - POSTGRES_DB=teamd_production
    ports:
      - "5434:5434"
    command: -p 5434
    expose:
      - 5434
  tvvldap:
    container_name: tvv-ldap
    image: osixia/openldap:latest
    restart: unless-stopped
    ports:
      - '10389:10389'
      - '10636:10636'
    command: [ "--copy-service" ]
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_BASE_DN: "dc=ad,dc=team1,dc=com"
      LDAP_ORGANISATION: "TVV"
      LDAP_DOMAIN: "ad.team1.com"
      LDAP_TLS: "false"
      LDAP_PORT: "10389"
    volumes:
      - ./ldapdata.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap-data.ldif
